import {
  Endpoint,
  Incident,
  DiscoveredHost,
  DnsAdCorrelationResult,
  LogRecord,
  SecurityModuleStatus,
} from '../types/security';

export const INITIAL_ENDPOINTS: Endpoint[] = [
  {
    id: 'ep-01',
    name: 'Portal Corporativo Carioca',
    ip: '10.0.0.10',
    url: 'https://carioca.com.do',
    method: 'GET',
    source: 'manual',
    status: 'up',
    httpStatus: 200,
    responseTime: 38,
    error: null,
    checkedAt: new Date(Date.now() - 15000).toISOString(),
    createdAt: '2026-03-15T08:00:00Z',
  },
  {
    id: 'ep-02',
    name: 'Gateway de Autenticación SSO',
    ip: '10.0.0.12',
    url: 'https://auth.carioca.com.do/oauth2/status',
    method: 'GET',
    source: 'manual',
    status: 'up',
    httpStatus: 200,
    responseTime: 62,
    error: null,
    checkedAt: new Date(Date.now() - 18000).toISOString(),
    createdAt: '2026-03-15T08:05:00Z',
  },
  {
    id: 'ep-03',
    name: 'Controlador de Dominio AD-DS (DNS/LDAP)',
    ip: '10.0.0.22',
    url: 'http://10.0.0.22:80',
    method: 'HEAD',
    source: 'discovery',
    status: 'degraded',
    httpStatus: 403,
    responseTime: 180,
    error: 'HTTP 403 Forbidden (IIS restringido)',
    checkedAt: new Date(Date.now() - 25000).toISOString(),
    createdAt: '2026-03-20T10:00:00Z',
  },
  {
    id: 'ep-04',
    name: 'Pasarela Jump Bastion Remota',
    ip: '10.0.0.18',
    url: 'https://jump-bastion.carioca.corp:8443',
    method: 'GET',
    source: 'manual',
    status: 'up',
    httpStatus: 200,
    responseTime: 112,
    error: null,
    checkedAt: new Date(Date.now() - 10000).toISOString(),
    createdAt: '2026-03-22T14:30:00Z',
  },
  {
    id: 'ep-05',
    name: 'Servicio API Legado de Almacén',
    ip: '10.0.0.35',
    url: 'http://10.0.0.35:8080/api/health',
    method: 'GET',
    source: 'csv',
    status: 'degraded',
    httpStatus: 503,
    responseTime: 950,
    error: 'Servicio temporalmente saturado',
    checkedAt: new Date(Date.now() - 5000).toISOString(),
    createdAt: '2026-03-24T09:15:00Z',
  },
  {
    id: 'ep-06',
    name: 'URL Sospechosa Detectada en DNS Sinkhole',
    ip: '185.220.101.5',
    url: 'https://carioca-secure-account-verify.xyz/login',
    method: 'GET',
    source: 'discovery',
    status: 'down',
    httpStatus: null,
    responseTime: 8000,
    error: 'Conexión bloqueada por regla perimetral EDR',
    checkedAt: new Date(Date.now() - 60000).toISOString(),
    createdAt: '2026-03-29T16:00:00Z',
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-101',
    title: 'Intento de fuerza bruta contra DC01-CARIOCA (EventID 4625)',
    category: 'Acceso no autorizado',
    description: 'Se registraron 34 intentos fallidos de autenticación en menos de 2 minutos contra la cuenta Administrador desde IP interna 10.0.0.140.',
    assetName: 'DC01-CARIOCA',
    assetIp: '10.0.0.22',
    severity: 'critical',
    status: 'investigating',
    reportedBy: 'Sistema NDR / Sensor',
    createdAt: '2026-03-30T10:15:00Z',
    updatedAt: '2026-03-30T11:00:00Z',
  },
  {
    id: 'inc-102',
    title: 'Instalación de servicio no registrado en servidor de base de datos',
    category: 'Persistencia / Malware',
    description: 'Generación de EventID 7045 con nombre de servicio aleatorio apuntando a carpeta %TEMP% en SQL-CORE-PROD.',
    assetName: 'SQL-CORE-PROD',
    assetIp: '10.0.0.45',
    severity: 'critical',
    status: 'open',
    reportedBy: 'EDR Local',
    createdAt: '2026-03-30T09:40:00Z',
    updatedAt: '2026-03-30T09:40:00Z',
  },
  {
    id: 'inc-103',
    title: 'Detección de software AnyDesk sin ticket de soporte autorizado',
    category: 'Shadow IT / Acceso Remoto',
    description: 'Tráfico saliente hacia servidores de retransmisión AnyDesk detectado desde estación financiera fuera del horario convenido.',
    assetName: 'DESKTOP-FIN-04',
    assetIp: '10.0.0.140',
    severity: 'high',
    status: 'investigating',
    reportedBy: 'NDR / Sensor de red',
    createdAt: '2026-03-29T17:20:00Z',
    updatedAt: '2026-03-30T08:30:00Z',
  },
  {
    id: 'inc-104',
    title: 'Tráfico HTTP sin cifrar en API de Almacén con datos de inventario',
    category: 'Transporte inseguro',
    description: 'La API 10.0.0.35:8080 expone transacciones de despacho sin HTTPS, permitiendo captura pasiva de credenciales básicas.',
    assetName: 'SRV-WMS-01',
    assetIp: '10.0.0.35',
    severity: 'medium',
    status: 'open',
    reportedBy: 'Auditoría Continua',
    createdAt: '2026-03-28T14:10:00Z',
    updatedAt: '2026-03-28T14:10:00Z',
  },
  {
    id: 'inc-105',
    title: 'Certificado TLS expirado en servidor de staging',
    category: 'Criptografía',
    description: 'El certificado comodín *.staging.carioca.corp expiró, provocando errores en pruebas de integración.',
    assetName: 'SRV-STG-NODE',
    assetIp: '10.0.0.88',
    severity: 'low',
    status: 'resolved',
    reportedBy: 'Monitor de Endpoints',
    createdAt: '2026-03-25T11:00:00Z',
    updatedAt: '2026-03-26T09:30:00Z',
  },
];

export const INITIAL_DISCOVERED_HOSTS: DiscoveredHost[] = [
  {
    ip: '10.0.0.22',
    hostname: 'dc01.carioca.com.do',
    name: 'DC01-CARIOCA',
    mac: '00:15:5D:8A:33:1F',
    manufacturer: 'Microsoft Hyper-V',
    ports: [53, 88, 135, 139, 389, 445, 636, 3389],
    services: [
      { port: 53, service: 'DNS', version: 'Microsoft Windows DNS 10.0', banner: 'DNS Microsoft Server 2022', evidence: 'Respuesta DNS RFC1035 verificada', riskLevel: 'low' },
      { port: 389, service: 'LDAP', version: 'Active Directory LDAP', banner: 'RootDSE dc=carioca,dc=com,dc=do', evidence: 'Directorio Active Directory respondiente', riskLevel: 'medium' },
      { port: 445, service: 'SMB', version: 'SMBv2/v3', banner: 'Windows Server 2022 Datacenter', evidence: 'Dialecto SMB 3.1.1 habilitado', riskLevel: 'high' },
      { port: 3389, service: 'RDP', version: 'CredSSP / NLA', banner: 'Terminal Server NLA activo', evidence: 'Escritorio remoto habilitado para administradores', riskLevel: 'high' },
    ],
    reachable: true,
    operationalImportance: 'critical',
    importanceReasons: ['Controlador de dominio AD-DS primario', 'Servidor de resolución DNS corporativo'],
    riskLevel: 'high',
    riskReasons: ['Puertos de administración 445 y 3389 accesibles en la subred'],
    firstSeen: '2026-03-01T00:00:00Z',
    lastSeen: new Date().toISOString(),
    status: 'active',
    source: 'Detección AD-DS y ARP',
  },
  {
    ip: '10.0.0.45',
    hostname: 'sql01.carioca.com.do',
    name: 'SQL-CORE-PROD',
    mac: '00:50:56:B2:11:4E',
    manufacturer: 'VMware',
    ports: [135, 445, 1433, 3389],
    services: [
      { port: 1433, service: 'Microsoft SQL Server', version: 'SQL Server 2019 CU18', banner: 'Microsoft SQL Server 15.0.4261', evidence: 'TDS protocol handshake response', riskLevel: 'high' },
      { port: 445, service: 'SMB', version: 'SMBv3', banner: 'Windows Server 2019', evidence: 'Puerto 445 abierto', riskLevel: 'high' },
    ],
    reachable: true,
    operationalImportance: 'critical',
    importanceReasons: ['Servidor de base de datos transaccional SQL Server'],
    riskLevel: 'high',
    riskReasons: ['Puerto 1433 accesible desde redes de puestos de trabajo'],
    firstSeen: '2026-03-05T00:00:00Z',
    lastSeen: new Date().toISOString(),
    status: 'active',
    source: 'Escaneo CIDR',
  },
  {
    ip: '10.0.0.98',
    hostname: 'nas-backup.carioca.corp',
    name: 'BACKUP-NAS01',
    mac: '3C:52:82:4D:99:A1',
    manufacturer: 'Hewlett-Packard',
    ports: [22, 80, 443, 445, 2049, 8080],
    services: [
      { port: 22, service: 'SSH', version: 'OpenSSH 8.9p1 Ubuntu', banner: 'SSH-2.0-OpenSSH_8.9p1', evidence: 'Banner SSH publicado', riskLevel: 'medium' },
      { port: 443, service: 'HTTPS', version: 'nginx 1.22.1', banner: 'nginx/1.22.1', evidence: 'Cabecera Server publicada', riskLevel: 'low' },
      { port: 2049, service: 'NFS', version: 'NFSv4', banner: 'Network File System', evidence: 'Servicio NFS abierto', riskLevel: 'high' },
    ],
    reachable: true,
    operationalImportance: 'critical',
    importanceReasons: ['Infraestructura central de copias de seguridad'],
    riskLevel: 'high',
    riskReasons: ['NFS 2049 expuesto sin restricción estricta de subred'],
    firstSeen: '2026-03-10T00:00:00Z',
    lastSeen: new Date().toISOString(),
    status: 'active',
    source: 'Escaneo CIDR',
  },
  {
    ip: '10.0.0.140',
    hostname: 'win-client-140.carioca.corp',
    name: 'DESKTOP-FIN-04',
    mac: 'F4:CE:46:77:22:9C',
    manufacturer: 'Dell',
    ports: [3389, 5900],
    services: [
      { port: 3389, service: 'RDP', version: 'Windows 11 Enterprise', banner: 'RDP Port', evidence: 'Puerto 3389 activo', riskLevel: 'high' },
      { port: 5900, service: 'VNC', version: 'UltraVNC Server', banner: 'RFB 003.008', evidence: 'Servicio VNC sin cifrado obligatorio', riskLevel: 'critical' },
    ],
    reachable: true,
    operationalImportance: 'medium',
    importanceReasons: ['Estación de usuario en departamento de finanzas'],
    riskLevel: 'critical',
    riskReasons: ['Puerto VNC 5900 abierto sin cifrado', 'Posible software de control no homologado'],
    firstSeen: '2026-03-28T08:00:00Z',
    lastSeen: new Date().toISOString(),
    status: 'active',
    source: 'ARP y Escaneo TCP',
  },
  {
    ip: '10.0.0.1',
    hostname: 'gw-core.carioca.corp',
    name: 'FW-PERIMETER-01',
    mac: 'B4:2E:99:3A:54:11',
    manufacturer: 'Lenovo / Fortinet',
    ports: [22, 443, 8443],
    services: [
      { port: 22, service: 'SSH', version: 'FortiOS SSH', banner: 'SSH-2.0-FortiSSH', evidence: 'Consola administrativa protegida por ACL', riskLevel: 'low' },
      { port: 443, service: 'HTTPS', version: 'FortiGate WebUI', banner: 'HTTPS Server', evidence: 'Interfaz de administración perimetral', riskLevel: 'low' },
    ],
    reachable: true,
    operationalImportance: 'critical',
    importanceReasons: ['Dispositivo perimetral y puerta de enlace predeterminada'],
    riskLevel: 'medium',
    riskReasons: ['Administración web HTTPS accesible internamente'],
    firstSeen: '2026-03-01T00:00:00Z',
    lastSeen: new Date().toISOString(),
    status: 'active',
    source: 'Gateway local',
  },
];

export const INITIAL_CORRELATION: DnsAdCorrelationResult = {
  checkedAt: new Date().toISOString(),
  serverIp: '10.0.0.22',
  dnsResponded: true,
  dnsResponseCode: 0,
  dnsError: null,
  ptrNames: ['dc01.carioca.com.do'],
  forwardAddresses: ['10.0.0.22'],
  dnsForwardMatchesServerIp: true,
  srvRecords: [
    { type: 'SRV', value: 'dc01.carioca.com.do', priority: 0, weight: 100, port: 389 },
    { type: 'SRV', value: 'dc02.carioca.com.do', priority: 10, weight: 100, port: 389 },
  ],
  adServerResponded: true,
  adError: null,
  domainName: 'carioca.com.do',
  domainControllers: [
    { name: 'DC01-CARIOCA', hostName: 'dc01.carioca.com.do', ip: '10.0.0.22' },
    { name: 'DC02-CARIOCA', hostName: 'dc02.carioca.com.do', ip: '10.0.0.23' },
  ],
  matchingDomainControllers: [
    { name: 'DC01-CARIOCA', hostName: 'dc01.carioca.com.do', ip: '10.0.0.22' },
  ],
  matchingComputers: [
    { name: 'DC01-CARIOCA', hostName: 'dc01.carioca.com.do', ip: '10.0.0.22' },
  ],
  sameServerConfirmed: true,
};

export const INITIAL_LOG_SAMPLES: LogRecord[] = [
  {
    EventID: 4625,
    TimeCreated: '2026-03-30 13:22:10',
    ProviderName: 'Microsoft-Windows-Security-Auditing',
    ProcessId: '748',
    ProcessName: 'lsass.exe',
    User: 'Administrator',
    Message: 'An account failed to log on. Subject: Security ID S-1-0-0, Account Name: Administrator. Failure Reason: Unknown user name or bad password. Workstation Name: DESKTOP-FIN-04.',
    source: 'Security',
  },
  {
    EventID: 4625,
    TimeCreated: '2026-03-30 13:22:14',
    ProviderName: 'Microsoft-Windows-Security-Auditing',
    ProcessId: '748',
    ProcessName: 'lsass.exe',
    User: 'Administrator',
    Message: 'An account failed to log on. Subject: Security ID S-1-0-0, Account Name: Administrator. Failure Reason: Unknown user name or bad password.',
    source: 'Security',
  },
  {
    EventID: 7045,
    TimeCreated: '2026-03-30 12:45:02',
    ProviderName: 'Service Control Manager',
    ProcessId: '612',
    ProcessName: 'services.exe',
    User: 'SYSTEM',
    Message: 'A service was installed in the system. Service Name: WshRemoteUpdateSvc, Service File Name: C:\\ProgramData\\Temp\\update_agent.exe, Service Type: user mode service.',
    source: 'System',
  },
  {
    EventID: 4104,
    TimeCreated: '2026-03-30 11:18:40',
    ProviderName: 'Microsoft-Windows-PowerShell',
    ProcessId: '4920',
    ProcessName: 'powershell.exe',
    User: 'rramirez',
    Message: 'Creating Scriptblock text (1 of 1): powershell.exe -ExecutionPolicy Bypass -NoProfile -EncodedCommand JABjAGwAaQBlAG4AdAAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0AA==',
    source: 'PowerShell/Operational',
  },
  {
    EventID: 1000,
    TimeCreated: '2026-03-30 10:05:12',
    ProviderName: 'Application Error',
    ProcessId: '8294',
    ProcessName: 'AnyDesk.exe',
    User: 'finanzas02',
    Message: 'Faulting application name: AnyDesk.exe, version: 8.0.4.0, time stamp: 0x6589abcd. Remote desktop tunnel established to external relay.',
    source: 'Application',
  },
  {
    EventID: 5007,
    TimeCreated: '2026-03-30 08:30:19',
    ProviderName: 'Microsoft-Windows-Windows Defender',
    ProcessId: '3128',
    ProcessName: 'MsMpEng.exe',
    User: 'SYSTEM',
    Message: 'Windows Defender Antivirus Configuration has changed. Real-time protection was disabled by local registry override.',
    source: 'Windows Defender',
  },
  {
    EventID: 4688,
    TimeCreated: '2026-03-30 08:15:00',
    ProviderName: 'Microsoft-Windows-Security-Auditing',
    ProcessId: '540',
    ProcessName: 'cmd.exe',
    User: 'SYSTEM',
    Message: 'A new process has been created. Creator Subject ID: 4. Process Command Line: cmd.exe /c whoami /all > C:\\temp\\recon.txt',
    source: 'Security',
  },
];

export const INITIAL_MODULES: SecurityModuleStatus[] = [
  {
    name: 'F5 BIG-IP WAF',
    key: 'f5',
    status: 'configured',
    detail: 'Conector REST activo hacia proxy perimetral (F5_BASE_URL)',
    eventCount: 142,
  },
  {
    name: 'EDR Local & Host Monitor',
    key: 'edr',
    status: 'active',
    detail: 'Reglas de comportamiento heurístico sobre endpoints y procesos Windows',
    eventCount: 89,
  },
  {
    name: 'IDS / Detección de Intrusos',
    key: 'ids',
    status: 'active',
    detail: 'Detección en tiempo real de fallos de autenticación, escalación y persistencia',
    eventCount: 64,
  },
  {
    name: 'NDR / Sensor de Red & AD',
    key: 'ndr',
    status: 'active',
    detail: 'Auditoría continua de subredes CIDR, banners de servicio y correlación AD-DS',
    eventCount: 38,
  },
];
